DELIMITER $

CREATE FUNCTION FN_GET_CUSTOMER_NAME(IDCUSTOMER INT)
RETURNS VARCHAR(30)
DETERMINISTIC

BEGIN
    DECLARE CUSTOMER_NAME VARCHAR(30);
    
    SELECT NAME_CUSTOMER INTO CUSTOMER_NAME
    FROM CUSTOMER C
    INNER JOIN RESERVE R
    WHERE C.IDCUSTOMER = R.IDRESERVE;
    
    RETURN NAME_CUSTOMER;

END$

DELIMITER;

/* CHAMANDO FUNCTION */

SELECT FN_GET_CUSTOMER_NAME(1);