/* TABELA CUSTOMER */

/* PROCEDURE DE INSERT - TABELA CUSTOMER */

DELIMITER $

CREATE PROCEDURE SP_INS_CUSTOMER(P_NAME VARCHAR(30),
                                 P_CPF VARCHAR(30),
                                 P_PHONE VARCHAR(30),
                                 P_EMAIL VARCHAR(50))

BEGIN

        INSERT INTO CUSTOMER(NAME,CPF,PHONE,EMAIL) VALUES(P_NAME,P_CPF,P_PHONE,P_EMAIL);

END $

DELIMITER ;

/* CHAMANDO SP */

CALL SP_INS_CUSTOMER('JOAO','096.857.493-88','(56)948374231','JOAO@GMAIL.COM');

/* PROCEDURE DE UPDATE */

DELIMITER $

CREATE PROCEDURE SP_UPD_CUSTOMER(P_NAME VARCHAR(30),
                                 P_CPF VARCHAR(30),
                                 P_PHONE VARCHAR(30),
                                 P_EMAIL VARCHAR(50),
                                 P_IDCUSTOMER INT)

BEGIN

        UPDATE CUSTOMER SET NAME = P_NAME,
                            CPF = P_CPF,
                            PHONE = P_PHONE,
                            EMAIL = P_EMAIL

        WHERE IDCUSTOMER = P_IDCUSTOMER;

END $

DELIMITER ;

/* CHAMANDO SP */

CALL SP_UPD_CUSTOMER('MARCOS','957.463.968-00','(45)985647362','MARCOS@GMAIL.COM',2);

/* PROCEDURE DE DELETE */

DELIMITER $

CREATE PROCEDURE SP_DEL_CUSTOMER(P_IDCUSTOMER INT)

BEGIN

        DELETE FROM CUSTOMER WHERE IDCUSTOMER = P_IDCUSTOMER;

END $

DELIMITER ;

/* CHAMANDO SP */

CALL SP_DEL_CUSTOMER(1);

---------------- o~~~~~}=======================>--------------------

/* TABELA ROOM */

/* PROCEDURE DE INSERT - TABELA ROOM */

DELIMITER $

CREATE PROCEDURE SP_INS_ROOM(P_ROOM VARCHAR(30),
                             P_BEDS VARCHAR(30))

BEGIN

        INSERT INTO ROOM(ROOM,BEDS) VALUES(P_ROOM,P_BEDS);

END $

DELIMITER ;

/* CHAMANDO SP */

CALL SP_INS_ROOM('12','2');

/* PROCEDURE DE UPDATE - TABELA ROOM */

DELIMITER $

CREATE PROCEDURE SP_UPD_ROOM(P_ROOM VARCHAR(30),
                             P_BEDS VARCHAR(30),
                             P_IDROOM INT)

BEGIN

        UPDATE ROOM SET ROOM = P_ROOM,
                        BEDS = P_BEDS

        WHERE IDROOM = P_IDROOM;

END $

DELIMITER ;

/* CHAMANDO SP */

CALL SP_UPD_ROOM('13','3',2);

/* PROCEDURE DE DELETE - TABELA ROOM */

DELIMITER $

CREATE PROCEDURE SP_DEL_ROOM(P_IDROOM INT)

BEGIN

        DELETE FROM ROOM WHERE IDROOM = P_IDROOM;

END $

DELIMITER ;

/* CHAMANDO SP */

CALL SP_DEL_ROOM(1);

---------------- o~~~~~}=======================>--------------------

/* TABELA RESERVE */

/* PROCEDURE INSERT - TABELA RESERVE */

DELIMITER $

CREATE PROCEDURE SP_INS_RESERVE(P_TIME DATETIME)

BEGIN

        INSERT INTO RESERVE(TIME) VALUES(P_TIME);

END $

DELIMITER ;

/* CHAMANDO SP */

CALL SP_INS_RESERVE('2023-02-05 12:32:45');

/* PROCEDURE DE UPDATE - TABELA ROOM */

DELIMITER $

CREATE PROCEDURE SP_UPD_RESERVE(P_TIME DATETIME,
                                P_IDRESERVE INT)

BEGIN

        UPDATE RESERVE SET TIME = P_TIME

        WHERE IDRESERVE = P_IDRESERVE;

END $

DELIMITER ;

/* CHAMANDO SP */

CALL SP_UPD_RESERVE('2023-03-01 10:21:12',2);

/* PROCEDURE DE DELETE - TABELA ROOM */

DELIMITER $

CREATE PROCEDURE SP_DEL_RESERVE(P_IDRESERVE INT)

BEGIN

        DELETE FROM RESERVE WHERE IDRESERVE = P_IDRESERVE;

END $

DELIMITER ;

/* CHAMANDO SP */

CALL SP_DEL_RESERVE(2);

---------------- o~~~~~}=======================>--------------------

/* TABELA SERVICE */

/* PROCEDURE INSERT - TABELA SERVICE */

DELIMITER $

CREATE PROCEDURE SP_INS_SERVICE(P_TYPE_SERVICE VARCHAR(50),
                                P_DESCRIPTION VARCHAR(100),
                                P_PRICE FLOAT(10,2))

BEGIN

        INSERT INTO SERVICE(TYPE_SERVICE,DESCRIPTION,PRICE) VALUES(P_TYPE_SERVICE,P_DESCRIPTION,P_PRICE);

END $

DELIMITER ;

/* CHAMANDO SP */

CALL SP_INS_SERVICE('LIMPEZA','LIMPEZA COMPLETA DO QUARTO E TROCA DE ENXOVAL',25.00);

/* PROCEDURE DE UPDATE - TABELA SERVICE */

DELIMITER $

CREATE PROCEDURE SP_UPD_SERVICE(P_TYPE_SERVICE VARCHAR(50),
                                P_DESCRIPTION VARCHAR(100),
                                P_PRICE FLOAT(10,2),
                                P_IDSERVICE INT)

BEGIN

        UPDATE SERVICE SET TYPE_SERVICE = P_TYPE_SERVICE,
                           DESCRIPTION = P_DESCRIPTION,
                           PRICE = P_PRICE

        WHERE IDSERVICE = P_IDSERVICE;

END $

DELIMITER ;

/* CHAMANDO SP */

CALL SP_UPD_SERVICE('FRIGOBAR','CONSUMO DE REFRIGERANTE LATA 350ML',6.50,1);

/* PROCEDURE DE DELETE - TABELA SERVICE */

DELIMITER $

CREATE PROCEDURE SP_DEL_SERVICE(P_IDSERVICE INT)

BEGIN

        DELETE FROM SERVICE WHERE IDSERVICE = P_IDSERVICE;

END $

DELIMITER ;

/* CHAMANDO SP */

CALL SP_DEL_SERVICE(1);

---------------- o~~~~~}=======================>--------------------

/* TABELA RESERVE_SERVICE */

/* PROCEDURE DE INSERT - TABELA RESERVE_SERVICE */

DELIMITER $

CREATE PROCEDURE SP_INS_RESERVE_SERVICE(P_DATE DATETIME)

BEGIN

        INSERT INTO RESERVE_SERVICE(DATE) VALUES(P_DATE);

END $

DELIMITER ;

/* CHAMANDO SP */

CALL SP_INS_RESERVE_SERVICE('2023-05-23 09:20:23');

/* PROCEDURE DE UPDATE - TABELA RESERVE_SERVICE */

DELIMITER $

CREATE PROCEDURE SP_UPD_RESERVE_SERVICE(P_DATE DATETIME,
                                        P_IDRESERVE_SERVICE INT)

BEGIN

        UPDATE RESERVE_SERVICE SET DATE = P_DATE

        WHERE IDRESERVE_SERVICE = P_IDRESERVE_SERVICE;

END $

DELIMITER ;

/* CHAMANDO SP */

CALL SP_UPD_RESERVE_SERVICE('2023-03-10 01:04:12',4);

/* PROCEDURE DE DELETE - TABELA RESERVE_SERVICE */

DELIMITER $

CREATE PROCEDURE SP_DEL_RESERVE_SERVICE(P_IDRESERVE_SERVICE INT)

BEGIN

        DELETE FROM RESERVE_SERVICE WHERE IDRESERVE_SERVICE = P_IDRESERVE_SERVICE;

END $

DELIMITER ;

/* CHAMANDO SP */

CALL SP_DEL_RESERVE_SERVICE(4);

---------------- o~~~~~}=======================>--------------------

/* TABELA CHECKIN */

/* PROCEDURE DE INSERT - TABELA CHECKIN */

DELIMITER $

CREATE PROCEDURE SP_INS_CHECKIN(P_TIME_CHECKIN DATETIME)

BEGIN

        INSERT INTO CHECKIN(TIME_CHECKIN) VALUES(P_TIME_CHECKIN);

END $

DELIMITER ;

/* CHAMANDO SP */

CALL SP_INS_CHECKIN('2023-02-19 07:17:19');

/* PROCEDURE DE UPDATE - TABELA CHECKIN */

DELIMITER $

CREATE PROCEDURE SP_UPD_CHECKIN(P_TIME_CHECKIN DATETIME,
                                P_IDCHECKIN INT)

BEGIN

        UPDATE CHECKIN SET TIME_CHECKIN = P_TIME_CHECKIN

        WHERE IDCHECKIN = P_IDCHECKIN;

END $

DELIMITER ;

/* CHAMANDO SP */

CALL SP_UPD_CHECKIN('2023-02-19 02:01:34',1);

/* PROCEDURE DE DELETE - TABELA CHECKIN */

DELIMITER $

CREATE PROCEDURE SP_DEL_CHECKIN(P_IDCHECKIN INT)

BEGIN

        DELETE FROM CHECKIN WHERE IDCHECKIN = P_IDCHECKIN;

END $

DELIMITER ;

/* CHAMANDO SP */

CALL SP_DEL_CHECKIN(1);

---------------- o~~~~~}=======================>--------------------

/* TABELA CHECKOUT */

/* PROCEDURE DE INSERT - TABELA CHECKOUT */

DELIMITER $

CREATE PROCEDURE SP_INS_CHECKOUT(P_TIME_CHECKOUT DATETIME)

BEGIN

        INSERT INTO CHECKOUT(TIME_CHECKOUT) VALUES(P_TIME_CHECKOUT);

END $

DELIMITER ;

/* CHAMANDO SP */

CALL SP_INS_CHECKOUT('2023-02-20 07:10:09');

/* PROCEDURE DE UPDATE - TABELA CHECKOUT */

DELIMITER $

CREATE PROCEDURE SP_UPD_CHECKOUT(P_TIME_CHECKOUT DATETIME,
                                P_IDCHECKOUT INT)

BEGIN

        UPDATE CHECKOUT SET TIME_CHECKOUT = P_TIME_CHECKOUT

        WHERE IDCHECKOUT = P_IDCHECKOUT;

END $

DELIMITER ;

/* CHAMANDO SP */

CALL SP_UPD_CHECKOUT('2023-02-20 07:20:21',1);

/* PROCEDURE DE DELETE - TABELA CHECKOUT */

DELIMITER $

CREATE PROCEDURE SP_DEL_CHECKOUT(P_IDCHECKOUT INT)

BEGIN

        DELETE FROM CHECKOUT WHERE IDCHECKOUT = P_IDCHECKOUT;

END $

DELIMITER ;

/* CHAMANDO SP */

CALL SP_DEL_CHECKOUT(1);