START TRANSACTION;

CREATE DATABASE HOTEL;

USE HOTEL;

CREATE TABLE CUSTOMER(
    IDCUSTOMER INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(30) NOT NULL,
    CPF VARCHAR(30) NOT NULL,
    PHONE VARCHAR(30) NOT NULL,
    EMAIL VARCHAR(50)
);

CREATE TABLE ROOM(
    IDROOM INT PRIMARY KEY AUTO_INCREMENT,
    ROOM VARCHAR(30),
    BEDS VARCHAR(30)
);

CREATE TABLE RESERVE(
    IDRESERVE INT PRIMARY KEY AUTO_INCREMENT,
    TIME DATETIME,
    FK_ID_CUSTUOMER INT,
    FK_ID_ROOM INT
);

CREATE TABLE SERVICE(
    IDSERVICE INT PRIMARY KEY AUTO_INCREMENT,
    TYPE_SERVICE VARCHAR(50),
    DESCRIPTION VARCHAR(100),
    PRICE FLOAT(10,2)
);

CREATE TABLE RESERVE_SERVICE(
    IDRESERVE_SERVICE INT PRIMARY KEY AUTO_INCREMENT,
    DATE DATETIME,
    FK_ID_RESERVE INT,
    FK_ID_SERVICE INT
);

CREATE TABLE CHECKIN( 
    IDCHECKIN INT PRIMARY KEY AUTO_INCREMENT,  -- DEFINIR FK
    TIME_CHECKIN DATETIME,
    ID_RESERVE INT
);

CREATE TABLE CHECKOUT(
    IDCHECKOUT INT PRIMARY KEY AUTO_INCREMENT,  -- DEFINIR FK
    TIME_CHECKOUT DATETIME,
    ID_RESERVE INT
);

/* CRIANDO FOREIGN KEY */

ALTER TABLE RESERVE ADD FOREIGN KEY(FK_ID_CUSTOMER) REFERENCES CUSTOMER(IDCUSTOMER);
ALTER TABLE RESERVE ADD FOREIGN KEY(FK_ID_ROOM) REFERENCES ROOM(IDROOM);

ALTER TABLE RESERVE_SERVICE ADD FOREIGN KEY(FK_ID_RESERVE) REFERENCES RESERVE(IDRESERVE);
ALTER TABLE RESERVE_SERVICE ADD FOREIGN KEY(FK_ID_SERVICE) REFERENCES SERVICE(IDSERVICE);

COMMIT;




/* ALTERACOES */

ALTER TABLE SERVICE RENAME COLUMN TYPE TO TYPE_SERVICE; -- RENOMEANDO COLUNA - TABELA SERVICE

ALTER TABLE RESERVE_SERVICE ADD COLUMN IDRESERVE_SERVICE INT PRIMARY KEY AUTO_INCREMENT; -- ADICIONANDO COLUNA - TABELA RESERVE_SERVICE
ALTER TABLE RESERVE_SERVICE ADD COLUMN DATE DATETIME; -- ADICIONANDO COLUNA - TABELA RESERVE_SERVICE
ALTER TABLE RESERVE_SERVICE DROP COLUMN TYPE; -- APAGANDO COLUNA - TABELA RESERVE_SERVICE
ALTER TABLE CHECKIN ADD COLUMN IDCHECKIN INT PRIMARY KEY AUTO_INCREMENT; -- ADICIONANDO COLUNA - TABELA CHECKIN
ALTER TABLE CHECKOUT ADD COLUMN IDCHECKOUT INT PRIMARY KEY AUTO_INCREMENT; -- ADICIONANDO COLUNA - TABELA CHECKOUT

ALTER TABLE CHECKIN RENAME COLUMN TIME TO TIME_CHECKIN; -- RENOMEANDO COLUNA - TABELA CHECKIN
ALTER TABLE CHECKOUT RENAME COLUMN TIME TO TIME_CHECKOUT; -- RENOMEANDO COLUNA - TABELA CHECKOUT

ALTER TABLE CHECKIN RENAME COLUMN ID_RESERVE TO FK_IN_ID_RESERVE; -- RENOMEANDO FOREIGN KEY - TABELA CHECKIN
ALTER TABLE CHECKOUT RENAME COLUMN ID_RESERVE TO FK_OUT_ID_RESERVE; -- RENOMEANDO FOREIGN KEY - TABELA CHECKOUT

ALTER TABLE RESERVE RENAME COLUMN FK_ID_CUSTUOMER TO FK_ID_CUSTOMER; -- RENOMENADO FOREIGN KEY (POSSUIA ERRO DE DIGITACAO)

/* CRIANDO FOREIGN KEY */

ALTER TABLE CHECKIN ADD FOREIGN KEY(FK_IN_ID_RESERVE) REFERENCES RESERVE(IDRESERVE);
ALTER TABLE CHECKOUT ADD FOREIGN KEY(FK_OUT_ID_RESERVE) REFERENCES RESERVE(IDRESERVE);