START TRANSACTION;

CREATE DATABASE HOTEL;

USE HOTEL;

CREATE TABLE CUSTOMER(
    IDCUSTOMER INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(30) NOT NULL,
    CPF VARCHAR(30) NOT NULL,
    PHONE VARCHAR(30) NOT NULL,
    EMAIL VARCHAR(50)
);

CREATE TABLE ROOM(
    IDROOM INT PRIMARY KEY AUTO_INCREMENT,
    ROOM VARCHAR(30),
    BEDS VARCHAR(30)
);

CREATE TABLE RESERVE(
    IDRESERVE INT PRIMARY KEY AUTO_INCREMENT,
    TIME DATETIME,
    FK_ID_CUSTUOMER INT,
    FK_ID_ROOM INT
);

CREATE TABLE SERVICE(
    IDSERVICE INT PRIMARY KEY AUTO_INCREMENT,
    TYPE_SERVICE VARCHAR(50),
    DESCRIPTION VARCHAR(100),
    PRICE FLOAT(10,2)
);

CREATE TABLE RESERVE_SERVICE(
    TYPE VARCHAR(30),
    FK_ID_RESERVE INT,
    FK_ID_SERVICE INT
);

CREATE TABLE CHECKIN(
    ID_RESERVE INT,
    TIME DATETIME
);

CREATE TABLE CHECKOUT(
    ID_RESERVE INT,
    TIME DATETIME
);

/* CRIANDO FOREIGN KEY */

ALTER TABLE RESERVE ADD FOREIGN KEY(FK_ID_CUSTOMER) REFERENCES CUSTOMER(IDCUSTOMER);
ALTER TABLE RESERVE ADD FOREIGN KEY(FK_ID_ROOM) REFERENCES ROOM(IDROOM);

ALTER TABLE RESERVE_SERVICE ADD FOREIGN KEY(FK_ID_RESERVE) REFERENCES RESERVE(IDRESERVE);
ALTER TABLE RESERVE_SERVICE ADD FOREIGN KEY(FK_ID_SERVICE) REFERENCES SERVICE(IDSERVICE);

COMMIT;






ALTER TABLE SERVICE RENAME COLUMN TYPE TO TYPE_SERVICE;