START TRANSACTION;

-- CRIANDO USUÁRIO COM TODOS OS PRIVILEGIOS
CREATE USER 'ADMIN'@'LOCALHOST' IDENTIFIED BY 'ADMIN123';
GRANT ALL PRIVILEGES
ON HOTEL.*
TO ADMIN@LOCALHOST
WITH GRANT OPTION;

--

-- CRIANDO USUARIO COM ALGUNS PRIVILEGIOS
CREATE USER 'JOAO'@'LOCALHOST' IDENTIFIED BY '123';
GRANT SELECT, INSERT, UPDATE, DELETE
ON HOTEL.*
TO JOAO@LOCALHOST;

--

-- CRIANDO USUARIO APENAS COM PRIVILEGIO DE SELECT
CREATE USER 'MARCOS'@'LOCALHOST' IDENTIFIED BY '1234';
GRANT SELECT
ON HOTEL.*
TO MARCOS@LOCALHOST;

--

-- REMOVENDO PRIVILEGIO DE DELETE DE UM USUARIO
REVOKE DELETE 
ON HOTEL.*
FROM JOAO@LOCALHOST;

COMMIT;