-- CRIANDO VIEW COM JOIN ENTRE TABELAS
CREATE VIEW V_CUSTOMER_INFO
AS
    SELECT C.NAME_CUSTOMER, C.PHONE, C.EMAIL, R.TIME
    FROM CUSTOMER C
    INNER JOIN RESERVE R
    ON IDCUSTOMER = IDRESERVE;

/* CHAMANDO VIEW */

SELECT * FROM V_NAME_PHONE;